name: OITC
version: 1.0.5
author: Janhektor
main: de.janhektor.oitc.Main

commands:
  oitc:
    description: Allgemeine Infos.
  vote:
    description: Voten.
  setarenaspawn:
    description: Arena Spawn setzen.
